# Generated by Django 3.1.1 on 2020-09-20 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='current_bid',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='old_bid',
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('desciption', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('img_url', models.URLField()),
                ('active', models.BooleanField(default=False)),
                ('time', models.DateTimeField()),
                ('categories', models.ManyToManyField(blank=True, related_name='listing', to='auctions.Category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.listing'),
        ),
    ]
