# Generated by Django 3.1.1 on 2020-09-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200921_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='listing', to='auctions.Category'),
        ),
    ]
